# Lecture no 13 (Numpy):-

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array({1,2,3,4,5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


# Dimensions in array

arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

# 1d Array:-

In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


# 2d Array:-

In [6]:
arr = np.array([[1,2,3,4],[3,7,7,9]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [3 7 7 9]]
2


# 3d Array:-

In [7]:
arr = np.array([[[1,2,3,4],[1,2,3,5],[1,2,3,4]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [1 2 3 5]
  [1 2 3 4]]]
3


# Check Number Of Dimensions

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2,8], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Array

# Create array with 5 dimensions and verify that it has 5 dimensions:

In [9]:
e = np.array([1,2,3], ndmin=5)

print(e)
print("Number of dimensions:", e.ndim)

[[[[[1 2 3]]]]]
Number of dimensions: 5


In [10]:
d = np.array([[[[1,2,3,4]]]])
print(d)
print(d.ndim)

[[[[1 2 3 4]]]]
4


# Numpy Array Indexing

# Get the first element from the following array:-

In [11]:
arr = np.array([1,2,3,4])
print(arr[0])

1


# Get third and sixth and 8th elements from the following array and add them 

In [12]:
q = np.array([22,54,56,77,88,99,22,38,67,43,79.88,80])
print("the second element is", q[2])
print("the sixth element is", q[5])
print("the eight element is", q[8])
print("sum of this elements are", q[2]+q[5]+q[8])

the second element is 56.0
the sixth element is 99.0
the eight element is 67.0
sum of this elements are 222.0


# Access 2-D Arrays:-

In [13]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 20


In [14]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('2nd element on 1st row:', arr[0,3])

2nd element on 1st row: 40


In [15]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('2nd element on 1st row:', arr[1,0])

2nd element on 1st row: 60


In [16]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('2nd element on 1st row:', arr[1,4])

2nd element on 1st row: 100


# add the first element of row1 and last element 

In [17]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('First element of 1st row:', arr[0,0])
print('last element of 2nd row', arr[1,4])
print("sum is", arr[0,0]+arr[1,4])

First element of 1st row: 10
last element of 2nd row 100
sum is 110


# Access 3-D array

# Access the third element of the second array of the first arary

In [18]:
arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]])
print(arr[0,1,2])

6


# slicing of numpy arrays

In [19]:
import numpy as np

In [20]:
arr = np.array([1,2,3,4,5,8,9])
print(arr[1:5])

[2 3 4 5]


In [21]:
arr = np.array([1,2,3,4,5,8,9])
print(arr[::2])

[1 3 5 9]


# Slicing in 2D array

In [22]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [23]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:4])

[10 20 30 40]


# checking the data type of an array

In [24]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [25]:
arr = np.array(["animals","catx","birds"])
print(arr.dtype)

<U7


# creating array with a defined data type

In [26]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Create an array with 4 byte integer

In [27]:
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy array shape

# print the shape of a 2d array

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


# print the shape of a 3d array

In [29]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4]]])
print(arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

In [30]:
arr1 = np.array([1,2,3,7])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 7 4 5 6]


# Join 2D array

In [31]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,7],[8,9]])

arr = np.concatenate((arr1,arr2), axis=1)

print(arr)

[[1 2 5 7]
 [3 4 8 9]]


In [32]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,7],[8,9]])

arr = np.concatenate((arr1,arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 7]
 [8 9]]


# Splitting Numpy Arrays

# splitting the array in 3 parts:-

In [33]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# splitting the array in 4 parts:-

In [34]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel & flatten:-

In [35]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [36]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is", m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


# 4d multidimension

In [37]:
o = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(o)
print("dimension is", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [38]:
o = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(o)
print("dimension is", m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is", n.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


# Unique Function

In [42]:
k = np.array([1,2,5,4,7,8,2,3,45,5,60,9,8,7,6])
print(k)
x = np.unique(k)
print(x)

[ 1  2  5  4  7  8  2  3 45  5 60  9  8  7  6]
[ 1  2  3  4  5  6  7  8  9 45 60]


In [43]:
k = np.array([1,2,5,4,7,8,2,3,45,5,60,9,8,7,6])
print(k)
x = np.unique(k, return_index = True)
print(x)

[ 1  2  5  4  7  8  2  3 45  5 60  9  8  7  6]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 60]), array([ 0,  1,  7,  3,  2, 14,  4,  5, 11,  8, 10]))


In [44]:
o = np.array([1,2,5,4,7,8,2,3,45,5,60,9,8,7,6])
print(o)
n = np.unique(o, return_index = True, return_counts = True)
print(n)

[ 1  2  5  4  7  8  2  3 45  5 60  9  8  7  6]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 60]), array([ 0,  1,  7,  3,  2, 14,  4,  5, 11,  8, 10]), array([1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1]))


In [45]:
import numpy as np

o = np.array([1,2,5,4,7,8,2,3,45,5,60,9,8,7,6])
print("Original array:", o)

unique_values, indices, counts = np.unique(o, return_index=True, return_counts=True)

print("Unique values   :", unique_values)
print("First indices   :", indices)
print("Counts          :", counts)


Original array: [ 1  2  5  4  7  8  2  3 45  5 60  9  8  7  6]
Unique values   : [ 1  2  3  4  5  6  7  8  9 45 60]
First indices   : [ 0  1  7  3  2 14  4  5 11  8 10]
Counts          : [1 2 1 1 2 1 2 2 1 1 1]


# Delete

In [47]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


In [51]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x)
m = np.delete(x, 1, axis=0)
print()
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
